services:
  mysql:
    image: mysql:9.6
    command: --default-time-zone='+00:00'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
  #migrate:
    #image: amacneil/dbmate:latest
    #environment:
      #DATABASE_URL: ${DATABASE_URL}
    #volumes:
      #- ./db/migrations:/db/migrations:ro
    #command: ["--wait", "--migrations-dir=/db/migrations", "up"]
    #depends_on:
      #mysql:
        #condition: service_healthy
  tabletopper:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - .:/app
    env_file: "./server/.env"
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tts-network
volumes:
  db_data:
networks:
  tts-network:
    driver: bridge
