package pages

type EditCharacterPageData struct {
	CharacterID         string
	Header              CharacterHeader
	Name                string
	Race                string
	Background          string
	Classes             string
	Size                string
	Alignment           string
	XP                  string
	Languages           string
	Proficiencies       string
	PersonalityTraits   string
	Ideals              string
	Bonds               string
	Flaws               string
	Age                 string
	Height              string
	Weight              string
	Eyes                string
	Skin                string
	Hair                string
	Str                 string
	Dex                 string
	Con                 string
	Int                 string
	Wis                 string
	Cha                 string
	AC                  string
	Speed               string
	InitiativeBonus     string
	MaxHP               string
	CurrentHP           string
	TempHP              string
	SpellcastingAbility string
	SpellBonusMisc      string
	HitDice             string
	HitDiceSpent        string
	DeathSaveSuccesses  int
	DeathSaveFailures   int
	HeroicInspiration   bool
	Exhaustion          string
	Features            []Feature
	Derived             Derived
	Attacks             []Attack
	Equipped            []InventoryItem
	Prepared            []PreparedSpellGroup
	SpellSlots          []SpellLevel
}
