package main

import (
	"log/slog"
	"net/http"
	"strings"

	"tabletopper/internal/controllers"
	"tabletopper/internal/middleware"
)

func handler(app *controllers.App, auth middleware.Auth) http.Handler {
	csrf := http.NewCrossOriginProtection()
	return middleware.SecurityHeaders(csrf.Handler(routes(app, auth)))
}

func routes(app *controllers.App, auth middleware.Auth) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /{$}", auth.OptionalSession(app.Homepage))
	mux.HandleFunc("/", notFound)
	mux.HandleFunc("GET /sign-in", app.SignIn)
	mux.HandleFunc("GET /sign-up", app.SignUp)
	mux.HandleFunc("GET /authorize", app.Authorize)
	mux.HandleFunc("POST /logout", app.Logout)
	mux.HandleFunc("GET /tos", app.TOS)
	mux.HandleFunc("GET /privacy", app.PrivacyPolicy)
	mux.HandleFunc("GET /error", app.ServerError)
	mux.HandleFunc("GET /characters", auth.RequireSession(app.CharactersPage))
	mux.HandleFunc("POST /characters", auth.RequireSession(app.NewCharacterForm))
	mux.HandleFunc("GET /characters/{id}/edit", auth.RequireSession(app.CharacterPage))
	mux.HandleFunc("GET /characters/{id}/edit/inventory", auth.RequireSession(app.CharacterInventoryPage))
	mux.HandleFunc("GET /characters/{id}/edit/spells", auth.RequireSession(app.CharacterSpellsRedirect))
	mux.HandleFunc("GET /characters/{id}/edit/spells/{level}", auth.RequireSession(app.CharacterSpellLevelPage))
	mux.HandleFunc("DELETE /characters/{id}", auth.RequireSession(app.DeleteCharacter))
	mux.HandleFunc("POST /characters/{id}/avatar", auth.RequireSession(app.UploadCharacterAvatar))
	mux.HandleFunc("POST /account/avatar", auth.RequireSession(app.UploadAccountAvatar))
	mux.HandleFunc("POST /characters/{id}/share", auth.RequireSession(app.CreateCharacterShare))
	mux.HandleFunc("DELETE /characters/{id}/share", auth.RequireSession(app.RevokeCharacterShare))
	mux.HandleFunc("GET /characters/{id}/export.md", auth.RequireSession(app.ExportCharacter))
	mux.HandleFunc("POST /characters/{id}/identity", auth.RequireSession(app.SaveCharacterIdentity))
	mux.HandleFunc("POST /characters/{id}/abilities", auth.RequireSession(app.SaveCharacterAbilities))
	mux.HandleFunc("POST /characters/{id}/core-stats", auth.RequireSession(app.SaveCharacterCoreStats))
	mux.HandleFunc("POST /characters/{id}/vitals", auth.RequireSession(app.SaveCharacterVitals))
	mux.HandleFunc("POST /characters/{id}/proficiencies", auth.RequireSession(app.SaveCharacterProficiencies))
	mux.HandleFunc("POST /characters/{id}/personality", auth.RequireSession(app.SaveCharacterPersonality))
	mux.HandleFunc("POST /characters/{id}/appearance", auth.RequireSession(app.SaveCharacterAppearance))
	mux.HandleFunc("POST /characters/{id}/features", auth.RequireSession(app.SaveCharacterFeatures))
	mux.HandleFunc("POST /characters/{id}/bonuses/{kind}", auth.RequireSession(app.SaveCharacterBonuses))
	mux.HandleFunc("POST /characters/{id}/inventory", auth.RequireSession(app.AddInventoryItem))
	mux.HandleFunc("POST /characters/{id}/inventory/{itemId}", auth.RequireSession(app.SaveInventoryItem))
	mux.HandleFunc("DELETE /characters/{id}/inventory/{itemId}", auth.RequireSession(app.DeleteInventoryItem))
	mux.HandleFunc("POST /characters/{id}/attacks", auth.RequireSession(app.AddAttack))
	mux.HandleFunc("POST /characters/{id}/attacks/{attackId}", auth.RequireSession(app.SaveAttack))
	mux.HandleFunc("DELETE /characters/{id}/attacks/{attackId}", auth.RequireSession(app.DeleteAttack))
	mux.HandleFunc("POST /characters/{id}/spells/slots/{level}", auth.RequireSession(app.SaveSpellSlots))
	mux.HandleFunc("POST /characters/{id}/spells/{level}", auth.RequireSession(app.AddSpell))
	mux.HandleFunc("POST /characters/{id}/spells/{level}/{spellId}", auth.RequireSession(app.SaveSpell))
	mux.HandleFunc("DELETE /characters/{id}/spells/{level}/{spellId}", auth.RequireSession(app.DeleteSpell))
	mux.HandleFunc("GET /characters/{id}/edit/journal", auth.RequireSession(app.CharacterJournalPage))
	mux.HandleFunc("GET /characters/{id}/edit/journal/{entryId}", auth.RequireSession(app.CharacterJournalEntryPage))
	mux.HandleFunc("POST /characters/{id}/journal", auth.RequireSession(app.CreateJournalEntry))
	mux.HandleFunc("POST /characters/{id}/journal/{entryId}", auth.RequireSession(app.SaveJournalEntry))
	mux.HandleFunc("DELETE /characters/{id}/journal/{entryId}", auth.RequireSession(app.DeleteJournalEntry))
	mux.HandleFunc("POST /characters/{id}/journal/{entryId}/images", auth.RequireSession(app.UploadJournalImage))
	mux.HandleFunc("GET /characters/{id}/journal/{entryId}/images/{assetId}", auth.RequireSessionOr404(app.GetJournalImage))
	mux.HandleFunc("POST /characters/{id}/journal/{entryId}/share", auth.RequireSession(app.CreateJournalShare))
	mux.HandleFunc("DELETE /characters/{id}/journal/{entryId}/share", auth.RequireSession(app.RevokeJournalShare))
	mux.HandleFunc("GET /share/{token}", auth.OptionalSession(app.SharePage))
	mux.HandleFunc("POST /share/{token}", app.UnlockShare)
	mux.HandleFunc("POST /share/{token}/import", auth.RequireSession(app.ImportSharedMonster))
	mux.HandleFunc("GET /share/{token}/portrait", app.GetSharePortrait)
	mux.HandleFunc("GET /share/{token}/export.md", app.ExportShare)
	mux.HandleFunc("GET /share/{token}/images/{assetId}", app.GetShareImage)
	mux.HandleFunc("POST /account/settings", auth.RequireSession(app.SaveAccountSettings))
	mux.HandleFunc("POST /account/welcome", auth.RequireSession(app.CompleteOnboarding))
	mux.HandleFunc("POST /account/welcome/skip", auth.RequireSession(app.DismissOnboarding))
	mux.HandleFunc("GET /monsters", auth.RequireSession(app.MonstersPage))
	mux.HandleFunc("POST /monsters", auth.RequireSession(app.NewMonsterForm))
	mux.HandleFunc("GET /monsters/{id}/edit", auth.RequireSession(app.MonsterPage))
	mux.HandleFunc("DELETE /monsters/{id}", auth.RequireSession(app.DeleteMonster))
	mux.HandleFunc("POST /monsters/{id}/image", auth.RequireSession(app.UploadMonsterImage))
	mux.HandleFunc("POST /monsters/{id}/share", auth.RequireSession(app.CreateMonsterShare))
	mux.HandleFunc("DELETE /monsters/{id}/share", auth.RequireSession(app.RevokeMonsterShare))
	mux.HandleFunc("GET /monsters/{id}/export.md", auth.RequireSession(app.ExportMonster))
	mux.HandleFunc("POST /monsters/{id}/identity", auth.RequireSession(app.SaveMonsterIdentity))
	mux.HandleFunc("POST /monsters/{id}/abilities", auth.RequireSession(app.SaveMonsterAbilities))
	mux.HandleFunc("POST /monsters/{id}/combat", auth.RequireSession(app.SaveMonsterCombat))
	mux.HandleFunc("POST /monsters/{id}/defenses", auth.RequireSession(app.SaveMonsterDefenses))
	mux.HandleFunc("POST /monsters/{id}/description", auth.RequireSession(app.SaveMonsterDescription))
	mux.HandleFunc("POST /monsters/{id}/bonuses/{kind}", auth.RequireSession(app.SaveMonsterBonuses))
	mux.HandleFunc("POST /monsters/{id}/actions/{kind}", auth.RequireSession(app.AddMonsterAction))
	mux.HandleFunc("POST /monsters/{id}/actions/{kind}/{actionId}", auth.RequireSession(app.SaveMonsterAction))
	mux.HandleFunc("DELETE /monsters/{id}/actions/{kind}/{actionId}", auth.RequireSession(app.DeleteMonsterAction))
	mux.HandleFunc("GET /rooms", auth.RequireSession(app.RoomsPage))
	mux.HandleFunc("POST /rooms", auth.RequireSession(app.NewRoomForm))
	mux.HandleFunc("GET /rooms/join", auth.RequireSession(app.JoinRoomPage))
	mux.HandleFunc("GET /rooms/join/{code}", auth.RequireSession(app.JoinRoomPage))
	mux.HandleFunc("POST /rooms/join", auth.RequireSession(app.JoinRoomForm))
	mux.HandleFunc("GET /rooms/{id}", auth.RequireSession(app.RoomPage))
	mux.HandleFunc("POST /rooms/{id}/lock", auth.RequireSession(app.LockRoom))
	mux.HandleFunc("POST /rooms/{id}/unlock", auth.RequireSession(app.UnlockRoom))
	mux.HandleFunc("POST /rooms/{id}/close", auth.RequireSession(app.CloseRoom))
	mux.HandleFunc("POST /rooms/{id}/open", auth.RequireSession(app.OpenRoom))
	mux.HandleFunc("POST /rooms/{id}/leave", auth.RequireSession(app.LeaveRoom))
	mux.HandleFunc("DELETE /rooms/{id}", auth.RequireSession(app.DeleteRoom))
	mux.HandleFunc("POST /rooms/{id}/players/{player}/kick", auth.RequireSession(app.KickPlayer))
	mux.HandleFunc("POST /rooms/{id}/layers", auth.RequireSession(app.AddLayer))
	mux.HandleFunc("DELETE /rooms/{id}/layers/{layer}", auth.RequireSession(app.RemoveLayer))
	mux.HandleFunc("PATCH /rooms/{id}/layers/{layer}/name", auth.RequireSession(app.RenameLayer))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/move", auth.RequireSession(app.MoveLayer))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/activate", auth.RequireSession(app.ActivateLayer))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/map", auth.RequireSession(app.SetLayerMap))
	mux.HandleFunc("DELETE /rooms/{id}/layers/{layer}/map", auth.RequireSession(app.ClearLayerMap))
	mux.HandleFunc("POST /rooms/{id}/palette", auth.RequireSession(app.AddToPalette))
	mux.HandleFunc("DELETE /rooms/{id}/palette/{art}", auth.RequireSession(app.RemoveFromPalette))
	mux.HandleFunc("POST /rooms/{id}/tiles/clear", auth.RequireSession(app.ClearLayerTiles))
	mux.HandleFunc("POST /rooms/{id}/notes", auth.RequireSession(app.SetHexNote))
	mux.HandleFunc("POST /rooms/{id}/notes/reveal", auth.RequireSession(app.RevealHexNote))
	mux.HandleFunc("DELETE /rooms/{id}/notes", auth.RequireSession(app.RemoveHexNote))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/gm-map", auth.RequireSession(app.SetGMLayerMap))
	mux.HandleFunc("DELETE /rooms/{id}/layers/{layer}/gm-map", auth.RequireSession(app.ClearGMLayerMap))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/maps", auth.RequireSession(app.UploadRoomMap))
	mux.HandleFunc("POST /rooms/{id}/layers/{layer}/maps/{asset}", auth.RequireSession(app.RetryRoomMapTiling))
	mux.HandleFunc("POST /rooms/{id}/party-start", auth.RequireSession(app.SetPartyStart))
	mux.HandleFunc("POST /rooms/{id}/grid", auth.RequireSession(app.SetRoomGrid))
	mux.HandleFunc("POST /rooms/{id}/settings", auth.RequireSession(app.SetRoomSettings))
	mux.HandleFunc("POST /rooms/{id}/scenes", auth.RequireSession(app.SaveScene))
	mux.HandleFunc("POST /rooms/{id}/scenes/{scene}/open", auth.RequireSession(app.OpenScene))
	mux.HandleFunc("POST /rooms/{id}/scenes/{scene}/save", auth.RequireSession(app.SaveSceneChanges))
	mux.HandleFunc("POST /scenes/{scene}/autosave", auth.RequireSession(app.SetSceneAutosave))
	mux.HandleFunc("PATCH /scenes/{scene}/name", auth.RequireSession(app.RenameScene))
	mux.HandleFunc("POST /scenes/{scene}/duplicate", auth.RequireSession(app.DuplicateScene))
	mux.HandleFunc("DELETE /scenes/{scene}", auth.RequireSession(app.DeleteScene))
	mux.HandleFunc("POST /rooms/{id}/fog/fill", auth.RequireSession(app.FillLayerFog))
	mux.HandleFunc("POST /rooms/{id}/fog/clear", auth.RequireSession(app.ClearLayerFog))
	mux.HandleFunc("POST /rooms/{id}/drawing/clear", auth.RequireSession(app.ClearLayerDrawing))
	mux.HandleFunc("POST /rooms/{id}/tabletop/clear", auth.RequireSession(app.ClearTabletop))
	mux.HandleFunc("POST /rooms/{id}/spawn/tokens", auth.RequireSession(app.UploadSpawnToken))
	mux.HandleFunc("POST /rooms/{id}/spawn/avatars", auth.RequireSession(app.UploadSpawnAvatar))
	mux.HandleFunc("POST /rooms/{id}/spawn/monsters", auth.RequireSession(app.CreateSpawnMonster))
	mux.HandleFunc("POST /rooms/{id}/pawns/party", auth.RequireSession(app.SpawnParty))
	mux.HandleFunc("POST /rooms/{id}/pawns/layer", auth.RequireSession(app.MovePawnsToLayer))
	mux.HandleFunc("POST /rooms/{id}/pawns/shown", auth.RequireSession(app.SetPawnsShown))
	mux.HandleFunc("DELETE /rooms/{id}/pawns", auth.RequireSession(app.RemovePawns))
	mux.HandleFunc("POST /rooms/{id}/pawns/{pawn}", auth.RequireSession(app.UpdatePawn))
	mux.HandleFunc("POST /rooms/{id}/pawns/{pawn}/hp", auth.RequireSession(app.UpdatePawnHP))
	mux.HandleFunc("POST /rooms/{id}/pawns/{pawn}/name", auth.RequireSession(app.RenamePawn))
	mux.HandleFunc("POST /rooms/{id}/dice", auth.RequireSession(app.RollDice))
	mux.HandleFunc("POST /rooms/{id}/music", auth.RequireSession(app.LoadRoomMusic))
	mux.HandleFunc("POST /rooms/{id}/music/play", auth.RequireSession(app.PlayRoomMusic))
	mux.HandleFunc("POST /rooms/{id}/music/pause", auth.RequireSession(app.PauseRoomMusic))
	mux.HandleFunc("POST /rooms/{id}/music/stop", auth.RequireSession(app.StopRoomMusic))
	mux.HandleFunc("POST /rooms/{id}/music/loop", auth.RequireSession(app.LoopRoomMusic))
	mux.HandleFunc("POST /rooms/{id}/music/ended", auth.RequireSession(app.EndRoomMusic))
	mux.HandleFunc("GET /rooms/{id}/music/audio", auth.RequireSessionOr404(app.RoomMusicAudio))
	mux.HandleFunc("POST /rooms/{id}/initiative", auth.RequireSession(app.AddInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/sync", auth.RequireSession(app.SyncInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/roll", auth.RequireSession(app.RollInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/order", auth.RequireSession(app.OrderInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/next", auth.RequireSession(app.NextInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/clear", auth.RequireSession(app.ClearInitiative))
	mux.HandleFunc("POST /rooms/{id}/initiative/{entry}/activate", auth.RequireSession(app.ActivateInitiative))
	mux.HandleFunc("DELETE /rooms/{id}/initiative/{entry}", auth.RequireSession(app.RemoveInitiative))
	mux.HandleFunc("GET /socket/room/{id}", auth.RequireSessionOr404(app.RoomSocket))
	mux.HandleFunc("GET /assets", auth.RequireSession(app.AssetsPage))
	mux.HandleFunc("GET /assets/maps", auth.RequireSession(app.MapAssetsPage))
	mux.HandleFunc("GET /assets/terrain", auth.RequireSession(app.TerrainAssetsPage))
	mux.HandleFunc("GET /assets/tokens", auth.RequireSession(app.TokenAssetsPage))
	mux.HandleFunc("GET /assets/avatars", auth.RequireSession(app.AvatarAssetsPage))
	mux.HandleFunc("GET /assets/music", auth.RequireSession(app.MusicAssetsPage))
	mux.HandleFunc("POST /assets/tokens", auth.RequireSession(app.UploadToken))
	mux.HandleFunc("POST /assets/tokens/{id}", auth.RequireSession(app.ReplaceToken))
	mux.HandleFunc("PATCH /assets/tokens/{id}/name", auth.RequireSession(app.RenameToken))
	mux.HandleFunc("DELETE /assets/tokens/{id}", auth.RequireSession(app.DeleteToken))
	mux.HandleFunc("POST /assets/avatars", auth.RequireSession(app.UploadAvatar))
	mux.HandleFunc("POST /assets/avatars/{id}", auth.RequireSession(app.ReplaceAvatar))
	mux.HandleFunc("PATCH /assets/avatars/{id}/name", auth.RequireSession(app.RenameAvatar))
	mux.HandleFunc("DELETE /assets/avatars/{id}", auth.RequireSession(app.DeleteAvatar))
	mux.HandleFunc("POST /assets/terrain", auth.RequireSession(app.UploadTerrain))
	mux.HandleFunc("POST /assets/terrain/{id}", auth.RequireSession(app.ReplaceTerrain))
	mux.HandleFunc("PATCH /assets/terrain/{id}/name", auth.RequireSession(app.RenameTerrain))
	mux.HandleFunc("DELETE /assets/terrain/{id}", auth.RequireSession(app.DeleteTerrain))
	mux.HandleFunc("POST /assets/music", auth.RequireSession(app.StartMusicUpload))
	mux.HandleFunc("POST /assets/music/{id}/confirm", auth.RequireSession(app.ConfirmMusicUpload))
	mux.HandleFunc("PATCH /assets/music/{id}/name", auth.RequireSession(app.RenameMusic))
	mux.HandleFunc("DELETE /assets/music/{id}", auth.RequireSession(app.DeleteMusic))
	mux.HandleFunc("GET /assets/music/{id}/audio", auth.RequireSessionOr404(app.GetMusicAudio))
	mux.HandleFunc("POST /assets/maps", auth.RequireSession(app.UploadMap))
	mux.HandleFunc("DELETE /assets/maps/{id}", auth.RequireSession(app.DeleteMap))
	mux.HandleFunc("POST /assets/maps/{id}", auth.RequireSession(app.ReplaceMap))
	mux.HandleFunc("PATCH /assets/maps/{id}/name", auth.RequireSession(app.ReplaceMapName))
	mux.HandleFunc("POST /assets/maps/{id}/tiles", auth.RequireSession(app.RetryMapTiling))
	mux.HandleFunc("GET /assets/maps/{id}/tiles/{gen}/{z}/{tile}", auth.RequireSessionOr404(app.GetMapTile))
	mux.HandleFunc("GET /assets/images/{id}", auth.RequireSessionOr404(app.GetImage))
	mux.HandleFunc("GET /assets/images/{id}/preview", auth.RequireSessionOr404(app.GetImagePreview))
	mux.HandleFunc("GET /fragment/character/new", auth.Fragment(app.NewCharacterFragment))
	mux.HandleFunc("GET /fragment/character/sheet", auth.Fragment(app.CharacterSheetFragment))
	mux.HandleFunc("GET /fragment/character/feature-row", auth.Fragment(app.FeatureRowFragment))
	mux.HandleFunc("GET /fragment/character/journal-link", auth.Fragment(app.JournalLinkFragment))
	mux.HandleFunc("GET /fragment/character/journal-entries", auth.Fragment(app.JournalEntriesFragment))
	mux.HandleFunc("GET /fragment/character/journal", auth.Fragment(app.CharacterJournalFragment))
	mux.HandleFunc("GET /fragment/character/journal-share", auth.Fragment(app.JournalShareFragment))
	mux.HandleFunc("GET /fragment/character/share", auth.Fragment(app.CharacterShareFragment))
	mux.HandleFunc("GET /fragment/account/settings", auth.Fragment(app.AccountSettingsFragment))
	mux.HandleFunc("GET /fragment/account/welcome", auth.Fragment(app.AccountWelcomeFragment))
	mux.HandleFunc("GET /fragment/monster/new", auth.Fragment(app.NewMonsterFragment))
	mux.HandleFunc("GET /fragment/monster/share", auth.Fragment(app.MonsterShareFragment))
	mux.HandleFunc("GET /fragment/monster/list", auth.Fragment(app.MonsterListFragment))
	mux.HandleFunc("GET /fragment/monster/stat-block", auth.Fragment(app.MonsterStatBlockFragment))
	mux.HandleFunc("GET /fragment/monster/manual", auth.Fragment(app.MonsterManualFragment))
	mux.HandleFunc("GET /fragment/assets/maps/{id}/card", auth.Fragment(app.MapCardFragment))
	mux.HandleFunc("GET /fragment/room/new", auth.Fragment(app.NewRoomFragment))
	mux.HandleFunc("GET /fragment/room/members", auth.Fragment(app.RoomMembersFragment))
	mux.HandleFunc("GET /fragment/room/layer", auth.Fragment(app.RoomLayerFragment))
	mux.HandleFunc("GET /fragment/room/layers", auth.Fragment(app.RoomLayersFragment))
	mux.HandleFunc("GET /fragment/room/maps", auth.Fragment(app.RoomMapsFragment))
	mux.HandleFunc("GET /fragment/room/map-list", auth.Fragment(app.RoomMapListFragment))
	mux.HandleFunc("GET /fragment/room/map-card", auth.Fragment(app.RoomMapCardFragment))
	mux.HandleFunc("GET /fragment/room/grid", auth.Fragment(app.RoomGridFragment))
	mux.HandleFunc("GET /fragment/room/settings", auth.Fragment(app.RoomSettingsFragment))
	mux.HandleFunc("GET /fragment/room/scenes", auth.Fragment(app.RoomScenesFragment))
	mux.HandleFunc("GET /fragment/room/scene-name", auth.Fragment(app.RoomSceneNameFragment))
	mux.HandleFunc("GET /fragment/room/table-menu", auth.Fragment(app.RoomTableMenuFragment))
	mux.HandleFunc("GET /fragment/room/palette", auth.Fragment(app.RoomPaletteFragment))
	mux.HandleFunc("GET /fragment/room/hex", auth.Fragment(app.HexNoteFragment))
	mux.HandleFunc("GET /fragment/room/scene/save", auth.Fragment(app.RoomSceneSaveFragment))
	mux.HandleFunc("GET /fragment/room/spawn", auth.Fragment(app.RoomSpawnFragment))
	mux.HandleFunc("GET /fragment/room/spawn-list", auth.Fragment(app.RoomSpawnListFragment))
	mux.HandleFunc("GET /fragment/room/spawn-npc", auth.Fragment(app.RoomSpawnNPCFragment))
	mux.HandleFunc("GET /fragment/room/spawn-monster", auth.Fragment(app.RoomSpawnMonsterFragment))
	mux.HandleFunc("GET /fragment/room/pawn", auth.Fragment(app.RoomPawnFragment))
	mux.HandleFunc("GET /fragment/room/pawn/rename", auth.Fragment(app.RoomPawnRenameFragment))
	mux.HandleFunc("GET /fragment/room/condition-row", auth.Fragment(app.RoomConditionRowFragment))
	mux.HandleFunc("GET /fragment/room/stat-block", auth.Fragment(app.RoomStatBlockFragment))
	mux.HandleFunc("GET /fragment/room/dice", auth.Fragment(app.RoomDiceFragment))
	mux.HandleFunc("GET /fragment/room/music", auth.Fragment(app.RoomMusicFragment))
	mux.HandleFunc("GET /fragment/room/music/library", auth.Fragment(app.RoomMusicLibraryFragment))
	mux.HandleFunc("GET /fragment/room/initiative", auth.Fragment(app.RoomInitiativeFragment))
	mux.HandleFunc("GET /fragment/room/initiative/entry", auth.Fragment(app.RoomInitiativeEntryFragment))
	mux.HandleFunc("GET /fragment/room/initiative/round", auth.Fragment(app.RoomInitiativeRoundFragment))
	mux.HandleFunc("GET /fragment/room/debug/renderer", auth.Fragment(app.RoomDebugRendererFragment))
	mux.HandleFunc("GET /fragment/room/debug/events", auth.Fragment(app.RoomDebugEventsFragment))
	mux.HandleFunc("GET /fragment/room/debug/state", auth.Fragment(app.RoomDebugStateFragment))
	mux.HandleFunc("GET /fragment/room/debug/server", auth.Fragment(app.RoomDebugServerFragment))
	mux.HandleFunc("GET /fragment/assets/list", auth.Fragment(app.AssetListFragment))
	mux.HandleFunc("/fragment/", middleware.FragmentNotFound)
	static := http.FileServer(http.Dir("./public"))
	files := func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/") {
			notFound(w, r)
			return
		}
		w.Header().Set("Cache-Control", "public, max-age=3600")
		static.ServeHTTP(w, r)
	}
	for _, prefix := range []string{"/css/", "/js/", "/static/", "/images/"} {
		mux.HandleFunc("GET "+prefix, files)
	}
	return mux
}
func notFound(w http.ResponseWriter, r *http.Request) {
	slog.Warn("404 Not Found", "path", r.URL.Path)
	http.NotFound(w, r)
}
