// Code generated by internal/room/gen. DO NOT EDIT.
//
// Regenerate from ./server with:
//
//     go generate ./...
//
// and commit the result. TestProtocolTypesAreCurrent fails when this file and
// the Go types disagree, so a stale copy breaks the build rather than a table.
//
// The Go types in internal/room are the authority: the server validates every
// message, so its structs are what a message has to be. Nothing here is
// hand-edited, and nothing here is the place to add a field.

// The enumerations. Each one is generated from that type's own Values method
// in Go, which is the same list the server validates against.

export type ClearTrigger = "start" | "end";

export type ConditionColor = "blue" | "green" | "orange" | "pink" | "purple" | "red" | "white" | "yellow";

export type Diagonals = "equal" | "alternating";

export type FogMode = "reveal" | "hide";

export type GridLines = "off" | "solid" | "dashed";

export type HPBand = "healthy" | "bruised" | "bloody" | "veryBloody" | "nearDeath" | "dead";

export type PawnKind = "player" | "monster" | "npc" | "object";

export type PawnLabels = "none" | "default" | "full";

export type Role = "gm" | "player";

export type ShapeKind = "rect" | "poly";

export type Size = "tiny" | "small" | "medium" | "large" | "huge" | "gargantuan";

export type Snap = "off" | "cells" | "halfCells";


// The entities. These are the objects that appear inside a snapshot and
// inside the events that carry a whole entity.

export interface Condition {
	id: string;
	name: string;
	color: ConditionColor;
	duration: number;
	clear: ClearTrigger;
}

export interface FogShape {
	id: string;
	layerId: string;
	kind: ShapeKind;
	mode: FogMode;
	points: number[];
}

export interface Grid {
	lines: GridLines;
	cellSize: number;
	offsetX: number;
	offsetY: number;
	color: string;
	snap: Snap;
	feetPerCell: number;
	diagonals: Diagonals;
}

export interface Initiative {
	entries: InitiativeEntry[];
	active: string | null;
	round: number;
}

export interface InitiativeEntry {
	id: string;
	pawnId: string | null;
	name: string;
	initiative: number;
}

export interface Layer {
	id: string;
	name: string;
	map: MapRef | null;
	fogEnabled: boolean;
	fogPrefill: boolean;
}

export interface MapRef {
	assetId: string;
	gen: string;
	width: number;
	height: number;
	tileSize: number;
	maxZoom: number;
}

export interface Pawn {
	id: string;
	kind: PawnKind;
	layerId: string;
	name: string;
	image: string;
	x: number;
	y: number;
	z: number;
	size: Size;
	width: number;
	height: number;
	rotation: number;
	visible: boolean;
	hp: number | null;
	maxHp: number | null;
	hpBand: HPBand | null;
	ac: number | null;
	conditions: Condition[];
	ownerId: string | null;
	monsterId: string | null;
	characterId: string | null;
}

export interface PawnPosition {
	id: string;
	x: number;
	y: number;
}

export interface Player {
	id: string;
	name: string;
	avatar: string;
	characterId: string | null;
	characterName: string;
	role: Role;
	connected: boolean;
}

export interface RoomInfo {
	id: string;
	name: string;
	locked: boolean;
}

export interface SnapshotYou {
	id: string;
	role: Role;
}

export interface State {
	schema: number;
	seq: number;
	room: RoomInfo;
	table: Table;
	players: Player[];
	pawns: Pawn[];
	initiative: Initiative;
	fog: FogShape[];
	strokes: Stroke[];
}

export interface Stroke {
	id: string;
	by: string;
	layerId: string;
	color: string;
	width: number;
	points: number[];
	done: boolean;
}

export interface Table {
	layers: Layer[];
	activeLayer: string;
	grid: Grid;
	pawnLabels: PawnLabels;
	playersCanDraw: boolean;
}


// The commands: what a client sends. Every one carries a client correlation
// id, which comes back on an error so the client knows which of its
// outstanding requests was refused.

export interface FogAdd {
	type: "fog.add";
	cid: string;
	layer: string;
	kind: ShapeKind;
	mode: FogMode;
	points: number[];
}

export interface FogClear {
	type: "fog.clear";
	cid: string;
	layer: string;
}

export interface FogRemove {
	type: "fog.remove";
	cid: string;
	id: string;
}

export interface FogSetEnabled {
	type: "fog.setEnabled";
	cid: string;
	layer: string;
	enabled: boolean;
}

export interface FogSetPrefill {
	type: "fog.setPrefill";
	cid: string;
	layer: string;
	prefill: boolean;
}

export interface InitiativeClear {
	type: "initiative.clear";
	cid: string;
}

export interface InitiativeNext {
	type: "initiative.next";
	cid: string;
}

export interface InitiativeSet {
	type: "initiative.set";
	cid: string;
	entries: InitiativeEntry[];
	active: string | null;
}

export interface PawnDrag {
	type: "pawn.drag";
	cid: string;
	anchor: string;
	x: number;
	y: number;
	others: string[];
}

export interface PawnMove {
	type: "pawn.move";
	cid: string;
	anchor: string;
	x: number;
	y: number;
	others: string[];
}

export interface PawnRemove {
	type: "pawn.remove";
	cid: string;
	ids: string[];
}

export interface PawnSetConditions {
	type: "pawn.setConditions";
	cid: string;
	id: string;
	conditions: Condition[];
}

export interface PawnSetLayer {
	type: "pawn.setLayer";
	cid: string;
	ids: string[];
	layer: string;
}

export interface PawnSetVisible {
	type: "pawn.setVisible";
	cid: string;
	ids: string[];
	visible: boolean;
}

export interface PawnSpawn {
	type: "pawn.spawn";
	cid: string;
	kind: PawnKind;
	layer: string;
	x: number;
	y: number;
	visible: boolean;
	monsterId?: string | null;
	characterId?: string | null;
	assetId?: string | null;
	name?: string;
	size?: Size;
	hp?: number | null;
	maxHp?: number | null;
	ac?: number | null;
}

export interface PawnSpawnCharacters {
	type: "pawn.spawnCharacters";
	cid: string;
}

export interface PawnUpdate {
	type: "pawn.update";
	cid: string;
	id: string;
	name?: string | null;
	hp?: number | null;
	maxHp?: number | null;
	ac?: number | null;
	size?: Size | null;
	z?: number | null;
	width?: number | null;
	height?: number | null;
	rotation?: number | null;
}

export interface Ping {
	type: "ping";
	cid: string;
	layer: string;
	x: number;
	y: number;
}

export interface PlayerKick {
	type: "player.kick";
	cid: string;
	id: string;
}

export interface StrokeBegin {
	type: "stroke.begin";
	cid: string;
	id: string;
	layer: string;
	color: string;
	width: number;
	points: number[];
}

export interface StrokeClear {
	type: "stroke.clear";
	cid: string;
	layer: string;
}

export interface StrokeEnd {
	type: "stroke.end";
	cid: string;
	id: string;
}

export interface StrokeErase {
	type: "stroke.erase";
	cid: string;
	ids: string[];
}

export interface StrokeExtend {
	type: "stroke.extend";
	cid: string;
	id: string;
	points: number[];
}

export interface SyncRequest {
	type: "sync.request";
	cid: string;
}

export interface TableAddLayer {
	type: "table.addLayer";
	cid: string;
	name: string;
}

export interface TableClear {
	type: "table.clear";
	cid: string;
}

export interface TableClearLayerMap {
	type: "table.clearLayerMap";
	cid: string;
	layer: string;
}

export interface TableMoveLayer {
	type: "table.moveLayer";
	cid: string;
	layer: string;
	index: number;
}

export interface TableRemoveLayer {
	type: "table.removeLayer";
	cid: string;
	layer: string;
}

export interface TableRenameLayer {
	type: "table.renameLayer";
	cid: string;
	layer: string;
	name: string;
}

export interface TableSetActiveLayer {
	type: "table.setActiveLayer";
	cid: string;
	layer: string;
}

export interface TableSetGrid {
	type: "table.setGrid";
	cid: string;
	grid: Grid;
}

export interface TableSetLayerMap {
	type: "table.setLayerMap";
	cid: string;
	layer: string;
	assetId: string;
}

export interface TableSetOptions {
	type: "table.setOptions";
	cid: string;
	pawnLabels: PawnLabels;
	playersCanDraw: boolean;
}

export type Command =
	| FogAdd
	| FogClear
	| FogRemove
	| FogSetEnabled
	| FogSetPrefill
	| InitiativeClear
	| InitiativeNext
	| InitiativeSet
	| PawnDrag
	| PawnMove
	| PawnRemove
	| PawnSetConditions
	| PawnSetLayer
	| PawnSetVisible
	| PawnSpawn
	| PawnSpawnCharacters
	| PawnUpdate
	| Ping
	| PlayerKick
	| StrokeBegin
	| StrokeClear
	| StrokeEnd
	| StrokeErase
	| StrokeExtend
	| SyncRequest
	| TableAddLayer
	| TableClear
	| TableClearLayerMap
	| TableMoveLayer
	| TableRemoveLayer
	| TableRenameLayer
	| TableSetActiveLayer
	| TableSetGrid
	| TableSetLayerMap
	| TableSetOptions
	;

// The events: what the server broadcasts, in the past tense. An event is the
// server's version of what happened, which may differ from what was asked --
// snapped to the grid, resolved against the monster manual, or projected down
// to less than the commanding client can see.

export interface ErrorEvent {
	type: "error";
	seq: number;
	by?: string;
	cid: string;
	code: string;
	heading: string;
	message: string;
}

export interface FogAdded {
	type: "fog.added";
	seq: number;
	by?: string;
	shape: FogShape;
}

export interface FogCleared {
	type: "fog.cleared";
	seq: number;
	by?: string;
	layer: string;
}

export interface FogRemoved {
	type: "fog.removed";
	seq: number;
	by?: string;
	id: string;
}

export interface InitiativeUpdated {
	type: "initiative.updated";
	seq: number;
	by?: string;
	initiative: Initiative;
}

export interface PawnDragging {
	type: "pawn.dragging";
	seq: number;
	by?: string;
	pawns: PawnPosition[];
}

export interface PawnMoved {
	type: "pawn.moved";
	seq: number;
	by?: string;
	pawns: PawnPosition[];
}

export interface PawnRemoved {
	type: "pawn.removed";
	seq: number;
	by?: string;
	id: string;
}

export interface PawnSpawned {
	type: "pawn.spawned";
	seq: number;
	by?: string;
	pawn: Pawn;
}

export interface PawnUpdated {
	type: "pawn.updated";
	seq: number;
	by?: string;
	pawn: Pawn;
}

export interface Pinged {
	type: "pinged";
	seq: number;
	by?: string;
	layer: string;
	x: number;
	y: number;
}

export interface PlayerJoined {
	type: "player.joined";
	seq: number;
	by?: string;
	player: Player;
}

export interface PlayerKicked {
	type: "player.kicked";
	seq: number;
	by?: string;
	reason: string;
}

export interface PlayerLeft {
	type: "player.left";
	seq: number;
	by?: string;
	id: string;
}

export interface PlayerUpdated {
	type: "player.updated";
	seq: number;
	by?: string;
	player: Player;
}

export interface RoomClosed {
	type: "room.closed";
	seq: number;
	by?: string;
}

export interface RoomUpdated {
	type: "room.updated";
	seq: number;
	by?: string;
	room: RoomInfo;
}

export interface Snapshot {
	type: "snapshot";
	seq: number;
	by?: string;
	state: State;
	you: SnapshotYou;
	version: string;
}

export interface StrokeBegan {
	type: "stroke.began";
	seq: number;
	by?: string;
	stroke: Stroke;
}

export interface StrokeCleared {
	type: "stroke.cleared";
	seq: number;
	by?: string;
	layer: string;
}

export interface StrokeEnded {
	type: "stroke.ended";
	seq: number;
	by?: string;
	id: string;
}

export interface StrokeErased {
	type: "stroke.erased";
	seq: number;
	by?: string;
	ids: string[];
}

export interface StrokeExtended {
	type: "stroke.extended";
	seq: number;
	by?: string;
	id: string;
	points: number[];
}

export interface TableUpdated {
	type: "table.updated";
	seq: number;
	by?: string;
	table: Table;
}

export type Event =
	| ErrorEvent
	| FogAdded
	| FogCleared
	| FogRemoved
	| InitiativeUpdated
	| PawnDragging
	| PawnMoved
	| PawnRemoved
	| PawnSpawned
	| PawnUpdated
	| Pinged
	| PlayerJoined
	| PlayerKicked
	| PlayerLeft
	| PlayerUpdated
	| RoomClosed
	| RoomUpdated
	| Snapshot
	| StrokeBegan
	| StrokeCleared
	| StrokeEnded
	| StrokeErased
	| StrokeExtended
	| TableUpdated
	;

// The events that never touch the reducer. A ping fades, a drag ghost is
// drawn and forgotten, an error opens a dialog: none of them is state, and
// none of them is in the snapshot, because there is nothing to restore.
export const TRANSIENT_EVENTS: ReadonlySet<Event["type"]> = new Set([
	"error",
	"pawn.dragging",
	"pinged",
	"player.kicked",
	"room.closed",
]);
