// The port is checked against the original rather than against a description of
// it.
//
// internal/room/testdata/reducer holds two golden fixtures, one per audience,
// each an initial state and fifty-eight steps of (events, resulting state).
// They are generated by the Go tests from the Go reducer, so they are the
// server's own answer -- and this replays them through the TypeScript reducer
// and compares every step. A change to reduce.go regenerates the fixtures and
// fails this until the port follows, which is the only thing that keeps two
// implementations of one specification honest.
//
// IT NEEDS NO TEST FRAMEWORK. Node runs a .ts file directly when it uses
// erasable syntax only, which the tsconfig enforces, and node:test is in the
// standard library.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { Event, State } from "./protocol.ts";
import { reduce } from "./store.ts";

interface Step {
	name: string;
	events: Event[];
	state: State;
}

interface Fixture {
	role: string;
	initial: State;
	steps: Step[];
}

const fixtures = join(import.meta.dirname, "..", "..", "internal", "room", "testdata", "reducer");

for (const role of ["gm", "player"]) {
	test(`the ${role} audience converges on the server's state`, () => {
		const fixture = JSON.parse(readFileSync(join(fixtures, `${role}.json`), "utf8")) as Fixture;

		assert.equal(fixture.role, role, "the fixture is for another audience");
		assert.ok(fixture.steps.length > 0, "the fixture has no steps");

		const state = structuredClone(fixture.initial);

		for (const [at, step] of fixture.steps.entries()) {
			for (const event of step.events) {
				reduce(state, event);
			}

			assert.deepStrictEqual(
				state,
				step.state,
				`step ${at + 1} (${step.name}) left the client's room different from the server's`,
			);
		}
	});
}

// The fixtures are a scenario and not a catalog, so this is the assertion that
// they were worth replaying: between them they have to have exercised every
// event that changes state. An event nobody sends is an event whose reduction
// nobody has checked.
test("the fixtures between them exercise every event that changes state", () => {
	const seen = new Set<string>();
	for (const role of ["gm", "player"]) {
		const fixture = JSON.parse(readFileSync(join(fixtures, `${role}.json`), "utf8")) as Fixture;
		for (const step of fixture.steps) {
			for (const event of step.events) {
				seen.add(event.type);
			}
		}
	}

	const missing = [
		"room.updated",
		"table.updated",
		"player.joined",
		"player.updated",
		"player.left",
		"pawn.spawned",
		"pawn.updated",
		"pawn.removed",
		"pawn.moved",
		"initiative.updated",
		"fog.added",
		"fog.removed",
		"fog.cleared",
		"stroke.began",
		"stroke.extended",
		"stroke.ended",
		"stroke.erased",
		"stroke.cleared",
	].filter((type) => !seen.has(type));

	assert.deepStrictEqual(missing, [], "the scenario never produced these events");
});
