name: Deployment

on:
    push:
        branches:
            - release

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node and NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.0

            - name: Install NPM Packages
              run: npm ci

            - name: Compile
              run: npm run production

            - name: Deploy
              run: npm run deploy
              env:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            - name: Purge cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              if: success()
              with:
                  cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
                  cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
