name: Deployment

on:
    push:
        branches:
            - release

jobs:
    deploy-server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node and NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 18.14.0

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21.1'

            - name: Load SSH Key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{ secrets.SSHKEY }}

            - name: Compile Server
              run: go build -ldflags="-s -w"
              working-directory: server

            - name: Deploy Server
              run: rsync -azh --delete-after --exclude={'.ari.toml','.env','.env.example','.gitignore','/tmp'} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/tabletopper/
              working-directory: server
            
            - name: Install Client NPM Packages
              run: npm ci
              working-directory: client

            - name: Compile Client
              run: npm run production
              working-directory: client

            - name: Deploy Client
              run: rsync -azh --delete-after --exclude={'/public/static/config.js','/node_modules','/build','.gitignore','brixi.config.js','cssmonster.config.json','asset-manager.config.js','package.json','package-lock.json','tsconfig.json','/src'} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/tabletopper/
              working-directory: client

            - name: Install WSS NPM Packages
              run: npm ci
              working-directory: wss

            - name: Compile WSS
              run: npm run production
              working-directory: wss

            - name: Deploy WSS
              run: rsync -azh --delete-after --exclude={'.git','.env','.github','.gitignore','tsconfig.json','/src','/build'} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/tabletopper/
              working-directory: wss
            
            - name: Post Deployment
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                USERNAME: ${{ secrets.USERNAME }}
                PORT: 22
                KEY: ${{ secrets.SSHKEY }}
                script: systemctl restart tabletoper-server.service && systemctl restart tabletoper-wss.service

            - name: Purge cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              if: success()
              with:
                  cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
                  cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}

